FirstApplication/Models/Rating.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace FirstApplication.Models
{
    public class Rating
    {
        [Key]
        [DatabaseGenerated(databaseGeneratedOption: DatabaseGeneratedOption.Identity)]
        public string RatingId { get; set; }

        [Required]
        [StringLength(128)]
        [Display(Name = "User")]
        public string UserId { get; set; }

        [ForeignKey("UserId")]


        public virtual ApplicationUser User { get; set; }

        [Required]
        [StringLength(128)]
        [Display(Name = "Game")]
        public string GameId { get; set; }

        [ForeignKey("GameId")]

        public virtual Game Game { get; set; }

        [Display(Name = "Create Date")]
        [DatabaseGenerated(databaseGeneratedOption: DatabaseGeneratedOption.Identity)]
        public DateTime CreateDate { get; set; }

        [Display(Name = "Edit Date")]
        public DateTime EditDate { get; set; } = DateTime.UtcNow;

        [Range(0,9)]
        [Display(Name = "Rank")]
        public decimal Rank { get; set; }
    }
}

FirstApplication/Controllers/RatingsController.cs
using FirstApplication.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace FirstApplication.Controllers
{
    public class RatingsController : Controller
    {
        DataContext db = new DataContext();
        // GET: Ratings
        public ActionResult Index()
        {
            return View();
        }

        public Rating SetRating(string gameId, decimal rank)
        {
            Rating rating = new Rating();
            rating.Rank = rank;
            rating.GameId = gameId;
            rating.UserId = User.Identity.GetUserId();

            db.Ratings.Add(rating);
            db.SaveChanges();

            rating = db.Ratings
                .Include(x => x.Game)
                .Include(x => x.Game.Ratings)
                .Include(x => x.User)
                .SingleOrDefault(x => x.RatingId == rating.RatingId);
            return (rating);
           // return RedirectToAction("Details", "Games", new { id = gameId });
        }

        public PartialViewResult RatingsControl(string gameId)
        {
            Game model = db.Games.Find(gameId);

            return PartialView("_RatingsControl", model);
        }
    }
}

FirstApplication/Views/Ratings/_RatingsControl.cshtml
@model FirstApplication.Models.Game

@{
    if (Model.Ratings.Count > 0)
    {
        <p>The overall rating for @Model.Name is @Model.OverallRating</p>
    }
    else
    {
        <p> Be the first to rate @Model.Name</p>
    }
}

@{
    for (int i = 0; i < 10; i++)
    {
        <a href="#" name="Rank" data-rank="@i" data-gameId="@Model.GameId" ><i class="glyphicon glyphicon-star@(Model.OverallRating < i ? "-empty" : "")"></i></a>
    }

}

@*@{using (Html.BeginForm("SetRating", "Ratings"))
    {
        @Html.HiddenFor(x => x.GameId)
        for (int i = 0; i < 10; i++)
        {
            <input type="radio" id="Rank" name="Rank" value="@i" /> @i
        }
        <input type="submit" value="Submit" />
    }

}*@